apiVersion: v1
kind: Service
metadata:
  name: taskapi-service
spec:
  # O tipo LoadBalancer cria um balanceador de carga de rede na GCP com um IP público
  type: LoadBalancer 
  selector:
    app: taskapi # Encontra os pods com esta label para enviar tráfego
  ports:
  - protocol: TCP
    port: 80 # A porta pública que será exposta (HTTP padrão)
    targetPort: 8080 # A porta no container para onde o tráfego será redirecionado